# Generated by Django 6.1 on 2026-08-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=150, verbose_name='اسم العيادة')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='المعرف')),
                ('database_name', models.CharField(max_length=150, unique=True, verbose_name='اسم قاعدة البيانات')),
                ('database_host', models.CharField(default='127.0.0.1', max_length=255, verbose_name='Database Host')),
                ('database_port', models.PositiveIntegerField(default=5432, verbose_name='Database Port')),
                ('database_user', models.CharField(max_length=150, verbose_name='Database User')),
                ('database_password', models.CharField(max_length=255, verbose_name='Database Password')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('suspended', 'موقوف')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
