# Generated by Django 6.1 on 2026-08-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='اسم المستخدم')),
                ('password', models.CharField(max_length=255, verbose_name='كلمة المرور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_superuser', models.BooleanField(default=True, verbose_name='مدير النظام الأساسي')),
                ('full_name', models.CharField(blank=True, default='', max_length=150, verbose_name='الاسم الكامل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مدير المنصة',
                'verbose_name_plural': 'مدراء المنصة',
            },
        ),
    ]
