# Generated by Django 6.1 on 2026-08-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_platformadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformadmin',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='فريق العمل'),
        ),
        migrations.AddField(
            model_name='platformadmin',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر تسجيل دخول'),
        ),
    ]
