# Generated by Django 6.1 on 2026-08-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('queue_date', models.DateField()),
                ('queue_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('waiting', 'في الانتظار'), ('in_examination', 'جاري الكشف'), ('completed', 'تم الكشف')], default='waiting', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('examination_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['queue_number'],
                'constraints': [models.UniqueConstraint(fields=('queue_date', 'queue_number'), name='unique_daily_queue_number')],
            },
        ),
    ]
