# Generated by Django 6.1 on 2026-08-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='visit_type',
            field=models.CharField(choices=[('examination', 'كشف'), ('consultation', 'استشارة')], default='examination', max_length=20, verbose_name='نوع الزيارة'),
        ),
    ]
