# Generated by Django 6.1 on 2026-09-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_visit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='complaint',
            field=models.TextField(blank=True, default='', verbose_name='المرض / الشكوى الرئيسية'),
        ),
    ]
