# Generated by Django 6.1 on 2026-09-01 21:16

import django.db.models.deletion
import django.utils.timezone
import patients.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_complaint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=patients.models.patient_attachment_upload_path, verbose_name='الملف / الصورة')),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='وصف الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='patients.patient', verbose_name='المريض')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'مرفق مريض',
                'verbose_name_plural': 'مرفقات المرضى',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='عنوان الملاحظة')),
                ('content', models.TextField(verbose_name='الملاحظة / التشخيص')),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الزيارة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_notes', to=settings.AUTH_USER_MODEL, verbose_name='الدكتور')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'ملاحظة مريض',
                'verbose_name_plural': 'ملاحظات المرضى',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
    ]
